version: 1.17.{build}
image: Visual Studio 2019
build_script:
- ps: .\build.ps1
artifacts:
- path: 'bin**\*.nupkg'
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master
    appveyor_repo_tag: true 